# Acronyms and Abbreviations {.unnumbered}

| Acronym | Full Form |
|---------|----------|
| AfDB | African Development Bank |
| AI | Artificial Intelligence |
| API | Application Programming Interface |
| AUSAID | Australian Agency for International Development |
| CBK | Central Bank of Kenya |
| CGD | Citizen Generated Data |
| CMA | Capital Markets Authority |
| CoP | Code of Practice |
| CPI | Consumer Price Index |
| CSPA | Common Statistical Production Architecture |
| CSV | Comma-Separated Values |
| DFID | Department for International Development |
| DQAF | Data Quality Assessment Framework |
| EAC | East African Community |
| ESQAF | European Statistics Quality Assurance Framework |
| EU | European Union |
| FKE | Federation of Kenya Employers |
| GAMSO | Generic Activity Model for Statistical Organizations |
| GDP | Gross Domestic Product |
| GIZ | German Corporation for International Cooperation |
| GPS | Global Positioning System |
| GSBPM | Generic Statistical Business Process Model |
| HTML | HyperText Markup Language |
| IAOS | International Association for Official Statistics |
| IaSC | Inter-Agency Statistical Committee |
| ICT | Information and Communication Technology |
| IMF | International Monetary Fund |
| IRA | Insurance Regulatory Authority |
| ISI | International Statistical Institute |
| ISO | International Organization for Standardization |
| IT | Information Technology |
| KAM | Kenya Association of Manufacturers |
| KDHS | Kenya Demographic and Health Survey |
| KEPSA | Kenya Private Sector Alliance |
| KeSQAF | Kenya Statistical Quality Assurance Framework |
| KIHBS | Kenya Integrated Household Budget Survey |
| KIPPRA | Kenya Institute for Public Policy Research and Analysis |
| KNBS | Kenya National Bureau of Statistics |
| KRA | Kenya Revenue Authority |
| KSDS | Kenya Strategy for Development of Statistics |
| MAPs | Marrakech Action Plan for Statistics |
| MDA | Ministry, Department and Agency |
| ML | Machine Learning |
| MoU | Memorandum of Understanding |
| NQAF | National Quality Assurance Framework |
| NQWG | National Quality Working Group |
| NSA | Non-State Actor |
| NSO | National Statistical Office |
| NSS | National Statistical System |
| OECD | Organization for Economic Co-operation and Development |
| PARIS21 | Partnership in Statistics for Development in the 21st Century |
| PGISA | Principles Governing International Statistical Activities |
| PPI | Producer Price Index |
| QA | Quality Assurance |
| QC | Quality Control |
| QWG | Quality Working Group |
| ROSC | Reports on the Observance of Standards and Codes |
| SDG | Sustainable Development Goals |
| SDMX | Statistical Data and Metadata Exchange |
| SDDS | Special Data Dissemination Standard |
| ShASA | Strategy for the Harmonization of Statistics in Africa |
| Sida | Swedish International Development Cooperation Agency |
| SSC | Sector Statistics Committee |
| SSP | Sector Statistics Plan |
| SWOT | Strengths, Weaknesses, Opportunities, and Threats |
| TQM | Total Quality Management |
| UN | United Nations |
| UNCTAD | United Nations Conference on Trade and Development |
| UNECA | United Nations Economic Commission for Africa |
| UNFPA | United Nations Population Fund |
| UN-NQAF | United Nations National Quality Assurance Framework |
| UNFPOS | UN Fundamental Principles of Official Statistics |
| UNSD | United Nations Statistical Division |
| USAID | United States Agency for International Development |
| XML | eXtensible Markup Language |