# Implementation of the Quality Assurance Framework

The KNBS is responsible for spearheading the development of the national quality assurance framework in consultation with the stakeholders in the national data ecosystem. It will also ensure that the framework is adopted and that the national legislation and provision support its implementation across the national data ecosystem. This will guide the production of statistics as well as outline the criteria for monitoring and assessing the quality of statistics produced in the country. It will be an assurance that the players in the data ecosystem commit to continually assess and improve the statistics produced in the Country.

## Institutional Arrangements

The specific institutional arrangements and roles of the quality units, task forces, quality managers, quality champions and focal points, and quality networks, among other things, that are involved in quality assurance are expected to evolve over time. Quality management therefore must be institutionalized. The following institutional arrangements for the implementation of KeSQAF will be set up.

(i) **Quality Unit**

A quality unit will be maintained at KNBS for quality management and coordination within KNBS in order to maintain sufficient capacity to lead and support the implementation of quality management initiatives throughout KNBS, and to support other NSS members and producers of official statistics if required. Other major statistics producers within the NSS will be encouraged to establish their own internal quality units to support the work on quality within their organizations. As per the current organizational structure, the quality unit in KNBS is the Methods and Standards Section. The head of the section will be the Quality Manager for KeSQAF.

(ii) **Internal Quality Working Group**

An internal quality task force consisting of representatives of the quality unit and representatives from each of the other directorates of KNBS to serve as quality champions/focal points in their respective functional areas will be maintained. There is already an established Quality Working Group (QWG) at KNBS. The QWG will support KeSQAF implementation throughout KNBS. The QWG will serve as a forum in which quality related issues in the various aspects of KNBS operations can be addressed at both the strategic management and the operational level. The QWG will also serve as a mobilization mechanism for quality management initiatives, such as documentation workshops or specialized training workshops for improving quality, among other things. Other major producers of official statistics will be encouraged to establish their own internal task forces.

(iii) **Quality Assurance Managers**

In order to mainstream quality at functional areas, KNBS Heads of Divisions will be designated as Quality Assurance Managers and will be responsible for establishing the quality assurance plan, defining all the quality activities and quality indicators to be implemented and computed in their divisions.

(iv) **NSS-Wide Governance Body and NSS-Wide Advisory Body**

The National Quality Working Group (NQWG) will be an NSS-wide quality working group that provides overall support to the implementation and monitoring of the KeSQAF. Members of the NSS will be supported by the NQWG to establish their internal quality units to support the work of quality assurance within their organizations in the implementation of KeSQAF. The IaSC will ensure that each of the producers and suppliers in the NSS own and adhere to the standards and practices provided for in the KeSQAF. Within the NQWG will be the Technical Working Group on alternative sources of data which will ensure the criteria for ensuring quality are adhered to in the production of statistics by Non-State Actors (NSAs) and monitor the use of the Criteria for validating CGD. The NQWG will be responsible for determining the structure and level of detail of the KeSQAF and its revision; sensitization of the data ecosystem players on the KeSQAF; developing tools for assessment of quality and conducting quality assessments of data produced in the country; developing capacity building programmes and implementing them in the country; Setting up focus groups regarding several key challenges that most of the data producers will face, such as quality assurance of administrative data sources, policies regarding the incorporation of new data sources and data made available by new data providers from outside the NSS and the standardization of metadata, among other things; Guiding proposals for the amendment of legal acts and administrative regulations to include quality assurance; Cooperating with the national task force on the SDG indicators in developing an action plan on quality assurance; Proposing coordinated policies on quality assurance with regard to the use of data supplied by providers; Developing guidelines on the structure of the quality reports to be prepared by data producers and agreeing on a schedule for their submission; Coordinating user outreach, including user-producer dialogues. KNBS will provide a secretariat for the working groups.

## Training of Staff

Quality managers, focal points and managers of statistical products need to gain a thorough understanding of the basic concepts, objectives and tools of quality assurance, and the KeSQAF. Therefore, adequate training for NQWG members, KNBS heads of division and all members of KNBS will be undertaken. After the adoption of KeSQAF, a workshop with quality assurance managers and technical officers at KNBS; and other statistical units will be undertaken to conduct a first self-assessment. Such self-assessment establishes a baseline for KeSQAF implementation and ensures awareness, ownership and management support for further quality work.

## External and Internal Communication

KNBS will explicitly communicate its commitment to high quality and continuous improvement to its stakeholders in the form of a declaration on quality. The declaration will state the principles that guide the approach of KNBS to managing quality, the standards it follows and the commitments to which it can be held accountable in producing official statistics. The declaration on quality will be officially launched, be visible on the KNBS website and be actively introduced and promoted internally and externally to all stakeholders through quality seminars, quality campaigns or an annual quality week etc.

## Development of an Implementation Strategy and Implementation Actions

KNBS will develop a short-term action plan for quality improvements covering one financial year and a parallel mid and long-term strategy and action plan. Generally, quality assurance will be applied at the institutional level and/or at the process or product level. The action plan will detail the relevant principles to be applied either at the institutional, processes or product level. During implementation, KNBS will conduct a dialogue between data producers and users to provide information on quality and use its findings and conclusions alongside results from quality assessments and audits. It will also develop or review the existing subject matter quality assurance frameworks accordingly. As a best practice, GSBPM and GAMSO will be used for quality management across the NSS.

All members of the NSS will commit to continually assess, improve and report on the quality of official statistics, as well as on the quality of data and statistics used in the production of official statistics. This framework will also be applied to all data and statistics produced outside of the NSS that are disseminated with the help and support of members of the NSS and used for government decision-making, as deemed appropriate. KNBS, therefore, will ensure the adoption and endorsement of the mandate for quality assurance at the policy level by including it in national legislation or provisions.

## Assessment and Reporting

As part of quality management, statistical quality assessment is integral to the overall quality management system in statistics production. This will be conducted on the statistical products and processes but will also be extended to the statistical system and institutional environment. The methods adopted for statistical quality assessment will include quality indicators, quality reports, user surveys, external and self-assessments and auditing (internal or external quality reviews), peer reviews and labelling.

In line with international best practice, the overarching relationship between KeSQAF, GSBPM and GAMSO will be used for quality assessment for Levels A, B, C and D as well as guiding the development of additional assessment tools. The use of GSBPM will allow the evaluation of the statistical production process and its sub-processes which will help in the detection of errors and taking of appropriate actions to mitigate the risk of undesirable impacts on statistical products.

This will specifically assess:

i. product quality in terms of the five quality principles: relevance; accuracy and reliability; timeliness and punctuality; accessibility and clarity; and coherence and comparability.
ii. process quality in terms of four quality principles: methodological soundness; cost-effectiveness; appropriate statistical procedures; and managing respondent burden; and
iii. quality of the NSS and the institutional environment in terms of nine quality principles: coordination; relationships with stakeholders; statistical standards; professional independence; impartiality and objectivity; transparency; statistical confidentiality and data security; commitment to quality; and adequacy of resources.

The KNBS through the QWG will develop quality indicators for the assessment framework guided by the international best practices. In acknowledging the collaborative approach needed to adequately define and develop quality indicators, data producers and users will be continuously engaged in the creation and revision of a quality assessment framework document.

In general, the use of quality indicators, the production of quality reports and the conduct of user surveys are considered the basic level of quality assessment tools. Self-assessment and audits constitute the next level of quality assessment, while labeling can be looked upon as an advanced process.

### Quality Indicators

The KNBS through the QWG will define and develop quality indicators to measure compliance with the respective quality principles and requirements. During the development of quality indicators, those linked to GSBPM will be reviewed and used where applicable. Input from users will also be considered.

### Quality Reports

Quality reports describe the outcome of quality assessments according to quality indicators. These reports will convey necessary information to enable users to assess the quality of the product. Quality reports can also be an important monitoring tool for statistics producers and managers. The quality assessment framework will outline a standard reporting structure that allows for comparability of statistical programmes based on predetermined specific quality indicators.

### Obtaining Feedback from Users

KNBS has adopted the best practice of regularly consulting its data users about their needs and perceptions of data quality, through a user satisfaction survey. User feedback will be a distinct component of the quality assessment framework and KNBS commits to conducting follow up with data users through appropriate mediums. This will also form a basis for continuous improvement from user feedback.

### Conducting Assessments

Regular predetermined self and external assessments; internal and external quality audits and peer reviews will be the main tools used to conduct assessments. The QWG will develop self-assessment checklists to be used for systematic assessment of the quality of the statistical production process. Self-assessment will be conducted by members within their functional areas at both KNBS and NSS supported by the NQWG. Regardless of the assessment context, results will be used to assess the degree of compliance for each of the requirements and describe strengths and weaknesses to enhance quality in the statistics produced within and outside NSS; by extension, it will demonstrate transparency about the extent to which data quality standards are met.

### Labeling

The next level will involve comparing assessment results with defined standards and requirements. Labelling shows the extent to which a set of quality standards are met. The attachment of a label requires a procedure to guarantee that the message is appropriate and true. This is for designating statistics as official or assessing their adequacy in terms of quality reporting. Thereafter, predetermined labels will accompany the various levels of fulfilment of quality standards with corresponding explanatory notes for each label. The methods and procedures for labelling will be developed by KNBS.

## Quality Assurance for Statistics Compiled from Different Data Sources

Three types of statistics producers at the national level can be distinguished: KNBS, other producers of official statistics and other statistics producers outside of the NSS. Data providers are entities that own or hold the data used in the production of statistics (source data). All types of statistics producers can use any type or combination of data sources, be they statistical, administrative, or other data sources.

For the purposes of this KeSQAF, it is suggested that data sources be distinguished by their purpose and by the entity responsible for data compilation. While it is acknowledged that others may want to define and distinguish data sources differently according to their respective needs, the following definitions and classification of data sources are proposed for the purposes of this KeSQAF:

a) **Statistical data sources** are data collections created primarily for official statistical purposes by government agencies or other entities working on behalf of the government. Statistical data sources include statistical sample surveys, censuses and statistical registers. There are different types of censuses, such as population and housing censuses, business censuses and agriculture censuses, among other types. Sample surveys and statistical registers can cover different units, for example, individuals, households and businesses. Statistical registers can themselves be derived from different sources. For example, statistical business registers are often based on administrative data sources;

b) **Administrative data sources** are data sets created primarily for administrative purposes by government agencies or other entities working on behalf of the government. Administrative data sources include administrative registers of persons and legal entities and the records of ministries, departments and specialized agencies, such as tax returns, social services records and customs data, or data of regional or local administrations. In contrast to statistical data sources, administrative data sources are not created in response to the need for statistical data but as a part of a government function, such as the provision of services or taxation. In some cases, statistical agencies participate in the design and/or collection of administrative data. In addition, statistical agencies may be involved at different stages of the production process of administrative data, to ensure that the data will be usable for statistical purposes;

c) **Other data sources** include all data sets that are not created primarily for official statistical or administrative purposes but rather for commercial or other private purposes. Examples of other data sources include:
   i. Cross-country sample surveys by supranational organizations or international enterprises;
   ii. Data compiled and maintained by private professional organizations or business associations, or by non-profit institutions in general;
   iii. Data and records compiled and maintained and/or owned by enterprises that cover large parts of the population of statistical units, in particular e-commerce, media and telecommunications providers, but also other enterprises that provide services directly to individuals or businesses, such as insurance companies, banks and airlines;
   iv. Earth observation and remote sensing;
   v. Thematic mapping and monitoring systems (e.g., field-monitoring stations for water quality, air pollution, etc.);
   vi. Research/scientific and pilot studies and
   vii. Citizen-generated data.

Interest in the use of other data sources (including the data sources covered by the term "big data") for the compilation of official statistics has been growing over the years. With the adoption of the 2030 Agenda for Sustainable Development and given the global and national data required to measure progress towards the SDGs, the use of other "new" data sources was identified as one of the top priorities for NSSs. Considering both the benefits and concerns/limitations of the use of the new data sources in official statistics, the United Nations Statistical Commission promoted their use and, at the same time, emphasized "the importance of ensuring the quality of data derived from new sources and new data providers, including those outside the official statistical system".

The Bureau will develop guidelines and criteria for assessing "other data sources" for use in reporting for national or sub-national indicators.

## Continuous Improvement of KeSQAF

Since the global statistical community is progressive, there is a need to assure continuous quality improvements. Ongoing developments in quality management require responsiveness that can assure current and ongoing improvement in the quality assured. As such, monitoring of new information on quality and use of this in statistical production processes for improved outputs is an indispensable component in the implementation of KeSQAF.