# Introduction

In recent years, new data sources, data providers and statistics producers have emerged, fueled by technological advances and new demands for detailed and timely data for policy making to address various development agendas. This new data ecosystem poses challenges and opportunities for official statistics. For instance, in the future, national statistical offices may see their role as a producer of official statistics diminished while adopting a new role as a curator of data and statistics produced by others. There is, therefore, a need for a National Quality Assurance Framework (NQAF) that provides a coherent and holistic system for statistical quality management that guarantees trust in the quality of official statistics. Official statistics need to be produced in an objective, transparent and professionally independent manner, in order to achieve and maintain public trust (UNCTAD, 2019). In light of this, the UN-NQAF manual for Official Statistics was adopted in 2019 to guide countries in the implementation of their respective NQAF (United Nations, 2019). The 19 quality principles and their associated requirements from the United Nations National Quality Assurance Framework (UN NQAF) manual are all borrowed in the development of the Kenya Statistical Quality Assurance Framework (KeSQAF). KeSQAF aims to address quality assurance in different circumstances and situations, thereby supporting the country in safeguarding the role of official statistics as a trusted source of information in a changing environment. This section presents the rationale for developing the quality assurance framework, the benefits of KeSQAF and the policies, strategies and frameworks supporting KeSQAF. Definitions of the adopted quality dimensions are also presented in this section.