# Quality Context

## Rationale for a Quality Assurance Framework

The Kenya National Bureau of Statistics (KNBS) is the National Statistics office in Kenya and is mandated to collect, compile, analyse, publish, and disseminate statistical information for public use. It is the principal agency for official statistics produced in the country. Official statistics are not only indispensable inputs for planning, monitoring and assessing attainment of the targets of the national development agenda, strategic objectives of businesses and research objectives of academicians, but are also useful for other evidence-based decision-making.

Given KNBS's obligation to provide statistics that inform decision-making and the need to provide leadership to members of the NSS and other producers of statistics, there is a need for a framework to support the production of high-quality statistics. The UN NQAF manual recommends the use of the Generic Statistical Business Process Model (GSBPM) which provides a roadmap on the various sets of business processes required to produce official statistics. GSBPM outlines steps in the data production process that include, identification of needs, design, data collection and processing, data analysis and reporting, dissemination and documentation and lastly, evaluation. Care has to be taken to guard against errors in the statistical business process and to mitigate and/or correct deficiencies by providing supportive legal, administrative and technological infrastructure and institutional environment. This is the context in which KeSQAF has been developed to manage the quality of the organization's services, statistical processes and related products, as well as communication with stakeholders in a systematic and formalized way.

The quality assurance framework provides transparency and clarity necessary to manage and respond to data users' expectations, queries and demands while bolstering the credibility of the organization. It is the responsibility of KNBS to clearly articulate the concepts and definitions that form the basis for the statistics produced while outlining the methodologies used. It is also KNBS's responsibility to check on erroneous interpretation and misuse of statistics. This is especially useful for addressing instances when the reasonableness of statistics published across NSS is questioned by stakeholders whose concerns may be based on the limited understanding of the methodologies used in generating the statistics.

The KNBS is part of a global statistical system characterized by increasing interconnectedness, a dynamic knowledge economy and the use of rapidly changing technology that requires openness and adherence to scientific and professional standards, including the use of a common architectural framework that allows for the sharing and exchange of information. The Bureau, therefore, does not operate in isolation but with other producers of statistics locally, regionally and internationally. Information sharing with its partners necessitates adequate provision for access to data, with due regard for confidentiality, coherence and comparability of statistics. Kenya ascribes to global, continental and regional development agendas such as Agenda 2063 on Africa Charter for Development of Statistics and the 2030 Global Development Agenda for Sustainable Development implying that statistics of high quality are necessary for tracking progress in attaining these development goals.

The UN Fundamental Principles of Official Statistics (UNFPOS) and Principles Governing International Statistical Activities (PGISA) promote coordination and cooperation among national organizations for official statistics to improve systems of official statistics globally. Against this background, there is a need for modernization of the Bureau's statistical production and services which is also being driven by the need to reduce the response burden and improve efficiencies in the production of official statistics. Additionally, data users have an increasing demand for more timely and accurate data and there is growing competition from alternative data producers and researchers moving up the statistical value chain. This, therefore, requires that KNBS steps up in the implementation of its mandate to ensure that the statistics produced across NSS are of high quality.

## Benefits of KeSQAF

The quality assurance framework has a well-defined and responsive structure that provides context for quality concerns, activities and initiatives and explains the relationships between the various quality procedures and tools. The framework provides a single platform to record and reference the full range of current quality concepts, dimensions and practices and is forward-looking since it is flexible to take into account future actions and activities.

The quality assurance framework also serves to formalize both operational standards and criteria for evaluating the fitness of statistical data for their required purposes, as well as the methodologies used for data collection, processing, analysis and dissemination, and strategic and managerial issues of statistics.

In addition, KeSQAF aims to improve consistency and efficiency in the NSS by reducing duplication of efforts; normalizing the use of international concepts, definitions, classifications, standards, sampling frames, and methodologies, where appropriate; and, creating datasets that are responsive to data sharing demands.

KeSQAF aims at increasing effectiveness and efficiency in the production of statistics in the Country. The framework also forms a foundation for validating data from both primary and alternative sources.

## Policies, Strategies and Frameworks Supporting KeSQAF

The development and implementation of KeSQAF is supported by various legal frameworks, strategies, policies, procedures and statistical quality frameworks. These include the:

a. Statistics Act, 2006;

b. Kenya Strategy for Development of Statistics (KSDS);

c. ISO 9001:2015 standards;

d. Existing Data Quality Assessment Frameworks (DQAFs);

e. United Nations National Quality Assurance Framework (UN-NQAF);

f. UN Principles Governing International Statistical Activities;

g. African Charter on Statistics;

h. International Statistical Institute's (ISI) Declaration on Professional Ethics;

i. Statistical Data and Metadata Exchange (SDMX);

j. European Statistics (Eurostat) Code of Practice (CoP).