# Quality Concepts

Quality is a multidimensional concept, which means the degree to which a set of inherent characteristics fulfils requirements. Quality is in reference to statistical output, the statistical process that produced it, the institutional environment housing the process, or the whole statistical system. The KNBS adopts the "Fit for purpose" approach, whereby statistics produced are appropriate and are of necessary standards for their intended use. This, therefore, means that the users of statistics will be continually engaged so that data produced in the Country is of the highest standard, integrity and credibility and addresses gaps/needs of the users. Data quality is expressed in terms of dimensions. In line with international best practices and recommendations, KNBS has adopted 11 key quality dimensions for assuring statistical quality. These are relevance, accuracy, reliability, timeliness, punctuality, accessibility, clarity/interpretability, coherence, consistency, methodological soundness and integrity. It is important to note that these quality dimensions strongly focus on the quality of the statistical output and are, therefore, a subset of the 19 quality principles adopted in KeSQAF.

## Relevance

is the "degree to which statistical information meets the real or perceived needs of clients." This dimension of quality addresses how useful official statistics are for the issues that are important to users. Resource constraints necessitate the identification of and responsiveness to the most important needs among many user needs.

## Accuracy

refers to the "closeness of computations or estimates to the unknown exact or true values that the statistics were intended to measure." This reflects the degree of nearness that official statistics have achieved in correctly representing the phenomena they measure. This can be expressed in terms of quantitative measures of accuracy, including possible sources of error such as coverage, sampling, non-response and response error rates; or qualitative assessment indicators.

## Reliability

is closely associated with accuracy and speaks of the "closeness of the initial estimated value to the subsequent estimated value." Consistently large differences between subsequent estimates to an initial estimate suggest possible bias in the initial estimate, while random large gaps between subsequent estimates and an initial estimate may indicate a need to re-assess the timeliness of subsequent estimates.

## Timeliness

pertains to the "length of time between data availability and the event or phenomenon they describe." This references both:

a) the time lapse between the end of a reference date/period for data collection and receipt of the data for compilation and processing (timeliness of source data), and

b) the time lapse between the end of a reference date/period and data dissemination (timeliness of output).

## Punctuality

is closely associated with timeliness and is the "time lag between the actual delivery of the data and the target date when it should have been delivered." This relates to whether or not data are disseminated on scheduled release dates. Data that is punctual may still be considered untimely if the release date lags too far behind its reference period (i.e., the time of the occurrence of the event/phenomenon), rendering it less useful or useless for decision-making.

## Accessibility

refers to "the ease and conditions under which statistical information can be obtained." This relates not only to how easily data can be accessed by users but also to the form the data are in and the means through which users have access to the data.

## Clarity

is "the extent to which easily comprehensible metadata are available, where these metadata are necessary to give a full understanding of statistical data." It addresses whether or not statistical data are complemented by descriptive information about the data's quality and limitations and if additional assistance is available to users by providers to enable users to work with the data to meet their needs.

## Coherence

is the "adequacy of statistics to be combined in different ways and for different uses. It refers to comparisons between statistics for the same or largely similar populations." Coherence in statistics is the degree to which the data constitute a logical picture of the population they are describing. For example, in the domain of labour statistics, the employed and unemployed must account for 100 per cent of the labour force.

## Consistency

refers to statistics having "logical and numerical coherence."

## Methodological Soundness

is "the extent to which the methodology used to compile statistics complies with the relevant international standards, including the professional standards enshrined in the UN Fundamental Principles for Official Statistics."

## Integrity

refers to "values and related practices that maintain confidence in the eyes of users in the agency producing statistics and ultimately in the statistical product." It is adherence to ethical and professional standards to ensure that transparency, accountability, methodological soundness, and professional independence guide the policies and practices of producing and disseminating official statistics.