# Quality Assurance Principles and Requirements

The KeSQAF quality principles and associated requirements consist of four levels, ranging from overarching institutional and cross-institutional management and statistical production processes to the outputs:

**Level A**: Managing the statistical system;

**Level B**: Managing the institutional environment;

**Level C**: Managing statistical processes; and

**Level D**: Managing statistical outputs.

Each level contains a concise set of principles and requirements to guarantee quality in that aspect of quality assurance. These requirements are vital indicators that, when met, will ensure that provisions have been made to assure quality.

A list of elements to be assured, which supports and assists the implementation of the principles and requirements and provides more detail are stated below each requirement. The elements to be assured are good practices and should be followed or assured.

## Level A: Managing the Statistical System

The National Statistical System is the ensemble of the National Statistical Office, the KNBS, and other statistical units in Kenya that produce, provide, supply, use and disseminate official statistics on behalf of the Government of Kenya under the supervision and coordination of the Bureau. Coordination of this system and managing relations with all stakeholders is a precondition for the quality and efficient production of official statistics. Ensuring the use of common statistical standards throughout the system is an important part of this management.

### Principle 1: Coordinating the National Statistical System

Coordination of the work of the members of the NSS is essential for improving and maintaining the quality of official statistics. This Principle is supported by principle 8 of the Fundamental Principles of Official Statistics on national coordination.

**Requirement 1.1:** A statistical law establishes the responsibilities of the members of the national statistical system, including its coordination. Its members are identified in a legal or formal provision.

Elements to be assured:
i. The coordination role of KNBS is defined in the Statistics Act, 2006.
ii. The Statistics Act, 2006 specifies the requirements for official statistics and the scope of the NSS.
iii. Members of the NSS are identified in a formal document.
iv. Responsibilities of NSS members for the development, production and dissemination of official statistics are specified in the Statistics Act, 2006 and relevant regulations.

**Requirement 1.2:** There is a body and mechanisms for the coordination of the national statistical system for activities at the local, national, regional and international levels.

Elements to be assured:
i. KNBS is tasked with the coordination of the NSS.
ii. KNBS has mechanisms to ensure the coordination (including the exchange of data and statistics within the NSS) and the quality of official statistics.
iii. KNBS sets, monitors and reviews guidelines for the development, production and dissemination of official statistics.
iv. KNBS establishes and maintains engagement with advisory bodies, academic institutions and other regional and international bodies as appropriate.
v. KNBS coordinates data collection to improve cost-effectiveness and reduce respondent burden, in particular with regard to coordinating sample surveys.
vi. KNBS monitors the use of agreed standards, concepts, classifications and methods throughout the NSS.
vii. KNBS promotes and enhances data sharing within the NSS and liaisons with members of the extended data ecosystem regarding the sharing of data.
viii. KNBS promotes the sharing of technical knowledge and good statistical practices and ensures the provision of training, including the production of official statistics and SDG indicators.
ix. Processes for the evaluation of the quality of the statistics are developed and applied within the NSS.

**Requirement 1.3:** There is a mechanism for considering statistics produced outside the national statistical system and, if appropriate, for those statistics to become official.

Elements to be assured:
i. KNBS evaluates statistics produced outside the NSS for use as official statistics or alongside official statistics. Examples of such statistics are some of the SDG indicators.
ii. KNBS has the responsibility for the evaluation of the quality of relevant statistics outside the NSS as needed.
iii. KNBS has established a unit that discusses and provides support for the use of new data sources within the NSS.

**Requirement 1.4:** There is a national plan or programme for the development and production of official statistics.

Elements to be assured:
i. There is a multi-year National Plan known as Kenya Strategy for the Development of Statistics (KSDS) which guides the development and production of official statistics.
ii. KSDS covers the entire NSS.
iii. KSDS addresses quality assurance.
iv. KSDS is implemented through the Sector Statistics Plans (SSPs) for the NSS members.
v. KSDS is established in close consultation with statistics producers, users and data providers.
vi. KSDS is approved for implementation by Inter-Agency Statistics Committee (IaSC).
vii. The programmes and activities of KSDS are monitored regularly by KNBS.

### Principle 2: Managing Relationships with Data Users, Data Providers and Other Stakeholders

KNBS and Statistical Units should build and sustain good relationships with all their key stakeholders, including users, data providers, funding agencies, senior government officials, relevant community organizations, academia and the media. KNBS and Statistical Units should have access to all data necessary to satisfy the information needs of society effectively and efficiently. This Principle is supported mainly by principles 1 and 5 of the Fundamental Principles of Official Statistics on Professional Standards, Scientific Principles, and Professional Ethics and Sources of Official Statistics.

**Requirement 2.1:** Stakeholders are identified and consulted regarding their interests, needs and obligations.

Elements to be assured:
i. KNBS and Statistical Units clearly identify all their stakeholders.
ii. Processes are in place to consult stakeholders about their concerns, interests, needs and obligations.
iii. Stakeholders are kept informed of actions taken to address their needs and concerns.

**Requirement 2.2:** KNBS and Statistical Units have a strategy, and institutional arrangements are in place to engage with their users.

Elements to be assured:
i. User needs and how to engage with users are reflected in KNBS and Statistical Units' strategies, such as in the KSDS, Strategic Plan, among others.
ii. Service agreements or similar arrangements with the main users of the statistics are in place.
iii. KNBS and Statistical Units have a communication mechanism in place to respond to all user inquiries in a timely manner.
iv. Users can engage and request KNBS and Statistical Units for information in their preferred means of communication.
v. Processes and arrangements (such as user committees) are in place so that users can advise KNBS and the Statistical Units about their emerging needs and priorities and during the development of new or review of existing statistics.
vi. There are sector-specific user committees.

**Requirement 2.3:** KNBS and Statistical Units continuously maintain and develop cooperation with funding agencies, academic institutions and international statistical organizations, as appropriate.

Elements to be assured:
i. KNBS and Statistical Units work plans and budgets are shared with development partners as appropriate to ensure mutual understanding of funding requirements and trade-offs.
ii. KNBS and Statistical Units coordinate the development and maintenance of cooperation with the scientific communities to develop new statistics, improve methodology and promote the use of statistics.
iii. KNBS and Statistical Units cooperate with international and regional organizations in the area of statistics and with the statistical organizations of other countries.

**Requirement 2.4:** KNBS and if appropriate, other Statistical Units have the legal authority or some other formal provision to collect data for the development, production and dissemination of official statistics.

Elements to be assured:
i. The Statistics Act, 2006 provides appropriate provisions to guarantee KNBS and if appropriate, other Statistical Units the right to collect data for statistical purposes through surveys and censuses.
ii. Based on the Statistics Act, 2006, KNBS can apply appropriate sanctions, such as fines, if a response to obligatory statistical surveys or censuses is not received.

**Requirement 2.5:** KNBS and if appropriate, other Statistical Units have the legal authority or some other formal provision to obtain administrative data and adequate access to those data from other government agencies for statistical purposes.

Elements to be assured:
i. The Statistics Act 2006 provides appropriate provisions to guarantee KNBS and if appropriate, other Statistical Units the right to obtain or access administrative data in a timely manner.
ii. Where KNBS or Statistical Units do not have the legal right to obtain administrative data, memoranda of understanding that provide such access are in place.
iii. Access to administrative data is free of charge for KNBS and Statistical Units.
iv. Agreements with owners of administrative data are in place to operationalize data access which describe technical conditions for access and possibilities for linking the data with data from other administrative data sources.
v. KNBS and Statistical Units are involved in the design and development of administrative data sets in order to make them suitable for statistical purposes; this involvement extends to the possible discontinuation of such data sets.

### Principle 3: Managing Statistical Standards

Standards refer to a comprehensive set of statistical concepts, definitions, classifications and models, methods and procedures used to achieve the uniform treatment of statistical issues within or across processes and across time and space. The use of standards promotes the consistency and efficiency of statistical systems at all levels. This Principle is supported by principle 9 of the Fundamental Principles of Official Statistics on Use of International Standards.

**Requirement 3.1:** KNBS and Statistical Units cooperate in the development and implementation of international, regional and national statistical standards.

Elements to be assured:
i. KNBS actively works with other Statistical Units and international and regional statistical organizations in developing, reviewing, promoting and implementing statistical standards.
ii. KNBS has a mechanism for facilitating and coordinating the adoption and development of international, regional and national statistical standards and for supporting statistical programmes/Sectors in their efforts to adopt and develop such standards.
iii. All relevant staff in KNBS and Statistical Units are aware of statistical standards and any changes made to them.
iv. There is a repository and a list of all standard classifications available and accessible to all data producers, providers and data users.
v. The process for originating, developing and approving statistical standards involves statistics producers, data providers and data users.
vi. The impact of the adoption of new statistical standards is assessed, documented and communicated to users; where applicable, conversion tables are provided.
vii. KNBS and Statistical Units use conceptual frameworks, such as the System of National Accounts, that provide a basis for integrating statistical information.
viii. Statistical standards (concepts, definitions, classifications, etc.) are regularly reviewed in line with prevailing international standards.

**Requirement 3.2:** KNBS provides support and guidance to all data providers and producers of official statistics in the implementation of statistical standards.

Elements to be assured:
i. KNBS monitors the extent to which statistical standards are used by data producers of official statistics.
ii. Periodic reports are prepared with regard to compliance with international, regional and national statistical standards.
iii. Statistical standards are communicated and made available to all data providers and producers of official statistics.
iv. Plans and schedules for the development and application of new standards are communicated in advance.
v. KNBS assists other producers of statistics and data providers in the implementation of international, regional and national statistical standards as appropriate.

**Requirement 3.3:** Divergences from the international, regional or national statistical standards are kept to a minimum and are documented and explained to all stakeholders.

Elements to be assured:
i. Concordance tables for international, regional and national standard classifications are developed and made available in cases where diverging standards are used.
ii. The adopted standards (concepts, definitions, classifications and guidelines.) are explained to all stakeholders.
iii. Stakeholders are informed about compliance with international, regional and national statistical standards.

## Level B: Managing the Institutional Environment

The quality of the institutional environment is one of the prerequisites to ensuring the quality of statistics. Principles to be assured are professional independence, impartiality and objectivity, transparency, statistical confidentiality, quality commitment and the adequacy of resources.

### Principle 4: Assuring Professional Independence

KNBS and Statistical Units in the National Statistical System (NSS), should develop, produce and disseminate statistics without any political or other interference or pressure from other government agencies or policy, regulatory or administrative departments and bodies, the private sector or any other persons or entities. Such professional independence and freedom from inappropriate influence ensure the credibility of official statistics. This principle is supported mainly by principle 2 of the Fundamental Principles of Official Statistics on professional standards and ethics.

**Requirement 4.1:** A law or other formal provision explicitly declares that KNBS and if appropriate other Statistical Units are obligated to develop, produce and disseminate statistics without interference from other government agencies or policy, regulatory or administrative departments and bodies, including from within the Statistical Units, private sector or any other persons or entities.

Elements to be assured:
i. Professional independence of KNBS and Statistical Units is guaranteed by the laws and regulations under which the ministries, departments and agencies operate.

**Requirement 4.2:** The appointment of the heads of KNBS, and other Statistical Units where appropriate, is based on professional criteria and follows transparent procedures. Reasons for dismissal cannot include reasons affecting professional independence. The heads of KNBS and Statistical Units are of the highest professional calibre.

Elements to be assured:
i. The Statistics Act, 2006 provides a clear and detailed description of the procedure for the appointment of the Director General of KNBS.
ii. The rules applied for appointing, assigning positions and responsibilities and dismissing the heads of KNBS and Statistical Units are also based on professional competence and are transparent and free from political considerations.
iii. Processes are in place to ensure that the heads of KNBS and Statistical Units are of the highest professional calibre.
iv. The Director General of KNBS has sufficiently high hierarchical standing to ensure access to the political and administrative leadership of government bodies.
v. The heads of KNBS and Statistical Units have the necessary qualifications, knowledge and capacity.
vi. The basis and process for the termination or removal of the Director General of KNBS and the heads of the Statistical Units within the government that produce statistics are specified in the relevant laws and administrative regulations. These cannot include reasons related to professional independence.

**Requirement 4.3:** The head of KNBS has responsibility for the decisions on statistical methods, standards and procedures, and on the content and timing of statistical releases.

Elements to be assured:
i. The Director General of KNBS and the heads of the Statistical Units within the government that produce statistics decide independently on the basis of professional considerations, on the statistical methods, standards and procedures for the development, production and dissemination of official statistics.
ii. The reporting of KNBS to its administratively superordinate government bodies and ministries, department and agencies does not affect its professional independence.

### Principle 5: Assuring Impartiality and Objectivity

KNBS and Statistical Units should develop, produce and disseminate statistics in an objective manner with equal treatment for all users. Statistical Units should be impartial and develop, produce and disseminate statistics without undue influence from any stakeholder, including governments or any political parties, interest groups or enterprises. This principle is supported mainly by principle 1 of the Fundamental Principles of Official Statistics on relevance, impartiality, and equal access.

**Requirement 5.1:** Statistical releases are clearly distinguished from political/policy statements.

Elements to be assured:
i. Statistical releases and statements made to the media are objective and based strictly on the available evidence and do not take any position on a political issue.
ii. Appropriate internal and external communication strategies exist that include recognizable logos, designs or formats for the products of KNBS and Statistical Units, which identify them as being unaffiliated with any political or policy bodies.

**Requirement 5.2:** KNBS and Statistical Units implement a declaration or code of conduct or ethics which governs statistical practices, and compliance with it is followed up.

Elements to be assured:
i. There are ethical guidelines or a code of conduct for assuring impartiality and objectivity.
ii. The guidelines are available to the public. The implementation of the guidelines is monitored for effectiveness.

**Requirement 5.3:** Data sources and methodologies are chosen on an objective basis.

Elements to be assured:
i. Sources, concepts, methods and processes for the development, production and dissemination of data are chosen on the basis of statistical considerations, national and international principles and best practices.

**Requirement 5.4:** Statistical release dates and times are announced in advance.

Elements to be assured:
i. A publicly available and easily accessible release calendar containing information on the releases planned in the upcoming 12-month period exists.
ii. Statistics are released at a fixed date.
iii. Changes in the release calendar are announced in advance and their reasons are explained.
iv. The sharing of statistical results ahead of the official release (a "privileged pre-release") is kept to a minimum and is well justified and strictly controlled and documented.

**Requirement 5.5:** In cases where errors are detected, they are corrected as soon as possible, and users are informed as to how they affected the released statistics.

Elements to be assured:
i. There is an established publicly available revision policy on how to correct published data when errors are discovered.

**Requirement 5.6:** KNBS and Statistical Units comment publicly on statistical issues, mis-interpretation and misuse of official statistics, as appropriate.

Elements to be assured:
i. There is a formal policy entitling KNBS and Statistical Units to respond publicly on statistical issues, criticisms, misinterpretations, negative media reporting and misuse of official statistics.

### Principle 6: Assuring Transparency

Policies and management practices, and the terms and conditions under which statistics are developed, produced and disseminated and, if applicable, subsequently revised (including the legal basis and purposes for which the data are required), are documented and available to users, respondents, owners of source data and the public. This Principle is supported mainly by principle 3 of the Fundamental Principles of Official Statistics on transparency and accountability.

**Requirement 6.1:** The terms and conditions for producing and disseminating official statistics are available to the public.

Elements to be assured:
i. A standard procedure exists for ensuring that respondents understand the legal basis for a survey and the confidentiality provisions for the data that are collected.
ii. Information on data sources, statistical concepts and methods used for the development, production and dissemination of official statistics are publicly available.
iii. The information on statistical standards is available to the public.
iv. Advance notice of major changes in methodology, source data or statistical techniques is given.
v. The data dissemination policy is shared with the public.

**Requirement 6.2:** The terms and conditions for the governance and management of KNBS and Statistical Units are available to the public.

Elements to be assured:
i. The procedures to be followed for the appointment and dismissal of heads of KNBS and Statistical Units within the NSS and the hiring and release of staff are publicly available.
ii. The reporting and dialogue of KNBS and Statistical Units within the NSS with administratively superordinate government bodies is well defined, established and known to the public.
iii. The work programmes of KNBS and Statistical units within the NSS and periodic reports to describe progress are made available to the public on a regular basis.

### Principle 7: Assuring Statistical Confidentiality and Data Security

KNBS and Statistical units within the NSS should guarantee that the privacy of data providers (persons, households, enterprises and other data providers) will be protected, and that the information they provide will be kept confidential, will not be accessed by unauthorized internal or external users and will be used for statistical purposes only. This principle is supported by principle 6 of the Fundamental Principles of Official Statistics on confidentiality.

**Requirement 7.1:** Statistical confidentiality is guaranteed by law.

Elements to be assured:
i. The Statistics Act, 2006 and Data Protection Act, 2019 guarantee proper management of information received from respondents and data providers to ensure statistical confidentiality and data security.

**Requirement 7.2:** Appropriate standards, guidelines, practices and procedures are in place to ensure statistical confidentiality.

Elements to be assured:
i. Guidelines and instructions on the protection of statistical confidentiality throughout the statistical business process are provided to all staff of KNBS and Statistical units within the NSS.
ii. There are regular and continuous sensitization programmes for all staff on the concept of statistical confidentiality and best practices to ensure the privacy of the information provided.
iii. The organizational structure and arrangements for the development and implementation of practices for ensuring statistical confidentiality is adequate to cope with needs.
iv. Staff sign confidentiality agreements upon their appointment, which are also valid after staff leave KNBS or Statistical Units within the NSS.

**Requirement 7.3:** Strict protocols to safeguard data confidentiality apply to users with access to microdata for research or statistical purposes.

Elements to be assured:
i. Clear conditions for granting access to confidential data for scientific purposes are set in the statistical law or other formal provision.
ii. Confidentiality rules, disclosure control and microdata access procedures apply throughout the statistical business process.
iii. KNBS and Statistical units within the NSS monitor the use of microdata sets to identify any circumstances in which data confidentiality may be breached (e.g., through file matching), and take immediate corrective action to address such a situation.

**Requirement 7.4:** Penalties are prescribed for any willful breaches of statistical confidentiality.

Elements to be assured:
i. Legal or other provisions are in place that allow administrative, penal, and disciplinary sanctions for the violation of statistical confidentiality.
ii. Information on the provisions that allow sanctions for the violation of statistical confidentiality is shared with all staff and is available to the public.

**Requirement 7.5:** The security and integrity of data and their transmission is guaranteed by appropriate policies and practices.

Elements to be assured:
i. An IT security policy is in place and is known to the staff.
ii. Following the IT policy, appropriate physical security measures and processes are in place to ensure data and database security, in accordance with best practices and international standards.
iii. Regular security audits of the data security system are carried out.
iv. All access to data repositories and transmission channels is monitored.
v. While data are being transferred, the risk of a breach is assessed, and appropriate procedures are applied to eliminate or minimize this risk.

**Requirement 7.6:** The risk that individual respondents may be identified is assessed and managed.

Elements to be assured:
i. There should be a balance between the acceptable level of risk of identification of individual respondents and the usability of the data.
ii. Appropriate processes are in place to assess the risk of disclosure of sensitive information and the risk that individual respondents can be identified from the public release of statistics or of microdata, and procedures are applied in line with the data dissemination policy to minimize this risk.
iii. All procedures taken to adequately reduce the risk of identification are properly documented and made available as part of the metadata related to the statistical data set.
iv. Users are made aware that procedures to reduce the risk of identification have been implemented and that such procedures could lead to a loss of information.

### Principle 8: Assuring Commitment to Quality

Members within the NSS should be dedicated to assuring quality in their work and systematically and regularly identify strengths and weaknesses to continuously improve process and product quality. This principle is supported by principle 2 of the Fundamental Principles of Official Statistics on professional standards and ethics.

**Requirement 8.1:** There is a quality policy or a statement of KNBS and Statistical Units' commitment to quality, which is publicly available.

Elements to be assured:
i. There is a policy, declaration, or message about commitment to the quality of statistics is made publicly available and it clearly conveys and promotes the shared concern for the quality of all of its staff and includes information about trade-offs affecting the statistical work programme.
ii. KNBS and Statistical Units have quality guidelines that are made available to external users, at least in a summarized version.

**Requirement 8.2:** KNBS and Statistical Units promote a culture of continuous improvement.

Elements to be assured:
i. Methodology and processes are regularly documented.
ii. Good statistical practices are exchanged among and between KNBS and Statistical Units.
iii. Procedures are in place to ensure that the required documentation on quality is regularly updated.
iv. A quality assurance plan or similar mechanism is in place that describes the work standards, formal obligations (such as laws and internal rules) and quality control actions that prevent, monitor and evaluate errors and control the statistical production process.
v. Workplans, schedules and standard forms or templates are used for facilitating the updating of the documentation of quality assurance procedures and actions in a consistent way.
vi. KNBS and Statistical Units use KeSQAF as a basis for regular quality assessments (self-assessments and other assessments).
vii. KNBS and Statistical Units use KeSQAF which is based on one of the accepted global or regional frameworks.
viii. General quality systems or frameworks such as total quality management and ISO 9000 are utilized in conjunction with KeSQAF.
ix. Quality initiatives of international and regional statistical bodies are followed up, as appropriate.

**Requirement 8.3:** There is a specific unit responsible for quality management or the coordination of quality management within KNBS, and it receives necessary support to fulfil this role.

Elements to be assured:
i. A quality assurance manager, committee, unit or group of coaches or advisers is assigned responsibility for quality management.
ii. An agency-wide data quality task force is established and meets regularly.
iii. Quality issues are discussed with and by management regularly.

**Requirement 8.4:** The national statistical system staff receive training on quality management.

Elements to be assured:
i. Staff training and development programmes are in place to ensure that staff are aware of the quality policy, including the use of KeSQAF, and that staff have an understanding of how quality is assured. A staff awareness "campaign" is undertaken to emphasize KNBS's and Statistical Units' commitment to quality.

**Requirement 8.5:** Guidelines for implementing quality management are defined and made available to the public.

Elements to be assured:
i. Guidelines for implementing quality management are produced and issued which:
   - Describe the quality principles and framework followed
   - Describe the entire statistical process and identify relevant documentation for each stage of production
   - Describe the methods for monitoring the quality at each stage of the statistical production process
   - Identify the indicators (quality measures) for evaluating the quality of the main stages of production, including indicators for source data
ii. The guidelines, methodological manuals and handbooks on recommended practices for quality assurance are made available to the public.
iii. Mechanisms are in place to assure the quality of data collection (including the use of administrative data and other sources) and data editing.

**Requirement 8.6:** Indicators on statistical output quality are regularly measured, monitored, published and followed up to improve statistical products and processes.

Elements to be assured:
i. Quality reports that serve both producer and user perspectives are prepared, published as appropriate and updated regularly.
ii. Quality indicators are defined, measured and monitored for follow-up and improvements. Examples of quality indicators include:
   - References in media, hits on websites, results from user satisfaction surveys (relevance)
   - Standard deviations and other measures of accuracy, response rates (accuracy)
   - Number and size of revisions (reliability)
   - The length of time between the end of a reference period and the dissemination of the statistics (timeliness)
   - Rate of statistics published when announced (punctuality)
   - Respondent burden

**Requirement 8.7:** Statistical products and processes undergo periodic reviews.

Elements to be assured:
i. Periodic quality reviews of key products and processes to assess adherence to internal guidelines and international standards are performed.
ii. Reviewing teams are set up in which both internal and external experts can participate.
iii. KNBS and Statistical Units' internal reviewers are trained in auditing methods and tools.
iv. Improvement actions arising from the result of quality reviews are defined and scheduled for implementation.
v. Top management is informed of the results of reviews so they can follow up on improvement actions.
vi. Benchmarking of key statistical processes with KNBS and Statistical Units is carried out to identify good practices.
vii. Procedures are in place to monitor and manage the quality of different stages of the statistical production according to the GSBPM.
viii. Trade-offs within quality are systematically examined (e.g., trade-offs among accuracy, timeliness and costs).
ix. External experts (including from international organizations) conduct quality reviews, such as reviews of key statistical domains (e.g., the IMF Reports on the Observance of Standards and Codes) or other reviews, such as peer reviews, external audits and rolling reviews.

**Requirement 8.8:** Risk analyses addressing the quality of important statistical products and processes are performed.

Elements to be assured:
i. Risk and quality management are closely coordinated (e.g., through institutional arrangements and regular meetings if responsibilities for these activities are set out differently).
ii. Risks linked to core recommendations and principles of KeSQAF (e.g., lack of independence and confidentiality breaches) are analysed and measures are taken if needed to improve compliance.
iii. Risk analyses addressing the quality of different stages of the statistical production are conducted according to the GSBPM.
iv. Risk analyses addressing the quality of important statistical products such as population statistics and censuses, national accounts and consumer price indices are performed (e.g., risk of poor accuracy expressed by errors, poor timeliness and lack of comparability).

### Principle 9: Assuring Adequacy of Resources

The financial, human, and technological resources available to KNBS and Statistical Units should be adequate both in magnitude and quality and sufficient to meet their needs regarding the development, production and dissemination of statistics.

**Requirement 9.1:** Financial, human and technological resources are sufficient to implement statistical work and development programme.

Elements to be assured:
i. There are resource mobilization strategies such as a KSDS are in place.
ii. The strategic plan and annual work plan are feasible given the available resources.
iii. Costs (staff costs and other costs) of each stage of the production process are measured.

**Requirement 9.2:** Planning and management principles are aimed at the optimal use of available resources.

Elements to be assured:
i. Activities schedules and budgets are adhered to ensure efficiency in the utilisation of resources.
ii. Information technology (IT) is employed to increase efficiency.
iii. Standardization, integration and automation of statistical production and dissemination are pursued to increase the efficiency of operations and to save costs.

**Requirement 9.3:** KNBS and Statistical Units' use of resources is reviewed.

Elements to be assured:
i. Indicators on the use of human and financial resources are monitored centrally and regularly reported to management.
ii. The use of human resources is evaluated annually on the basis of established guidelines and procedures. The evaluation covers the allocation, performance and training needs of staff.
iii. Staff opinion/satisfaction surveys are conducted regularly.

## Level C: Managing Statistical Processes

International standards, guidelines and good practices are fully observed in the statistical processes used by KNBS and Statistical Units to develop, produce and disseminate official statistics, while constantly striving for innovation. The credibility of the statistics is enhanced by a reputation for good management and efficiency. The relevant principles to be assured are methodological soundness, cost-effectiveness, appropriate statistical procedures and managing the respondent burden.

### Principle 10: Assuring Methodological Soundness

In developing and producing statistics, KNBS and Statistical Units should use sound statistical methodologies based on internationally agreed standards, guidelines or best practices. Principle 10 is supported mainly by principle 2 of the Fundamental Principles of Official Statistics on professional standards, scientific principles, and professional ethics.

**Requirement 10.1:** The methodologies applied by KNBS, and Statistical Units are consistent with international standards, guidelines and good practices and are regularly reviewed and revised as needed.

Elements to be assured:
i. Organizational structures/unit for the development and application of sound statistical methods are commensurate to needs.
ii. Review and reporting processes are in place that allow the management of KNBS and Statistical Units to be assured that sound methodological approaches have been adopted and applied throughout the production process.
iii. The surveys' methodologies and the use of administrative data and other sources of data are evaluated periodically.
iv. Sampling design is based on sound methodology.
v. Proper follow-up procedures are planned and implemented in cases of non-response.
vi. Statistical editing procedures and imputation methods are based on sound methodology.
vii. When statistical modelling is used in the statistical production process (e.g., for seasonal adjustment), the validity of model assumptions is carefully considered and the impact on final estimates is evaluated.
viii. KNBS and Statistical Units review the methods used by external partners for the compilation of data and the production of statistics.

**Requirement 10.2:** KNBS and Statistical Units recruit qualified staff and conduct regular programmes to enhance their methodological skills.

Elements to be assured:
i. Staff of KNBS and Statistical Units are recruited on the basis of their qualifications and experience.
ii. Appropriate qualifications requirements are specified for all posts.
iii. Training and development programmes are in place to ensure the staff acquire and continuously update their methodological knowledge.
iv. Staff skills are regularly updated so that staff are able to utilize new data sources and tools.
v. Attendance of staff at relevant training courses and/or at national, regional or international conferences is encouraged.
vi. Exchange programmes among peers to enhance peer to peer learning.
vii. Knowledge management transfer or sharing among staff.
viii. Study tours.

**Requirement 10.3:** KNBS and Statistical Units choose data sources taking into account accuracy and reliability, timeliness, cost, the burden on respondents and other necessary considerations.

Elements to be assured:
i. The use of data from surveys, censuses, administrative, and alternative sources which include big data, Citizen Generated Data or other sources of data, is constantly evaluated. The KNBS will develop and continually improve guidelines to be used to validate the data from alternative sources (see the Criteria for Validating Citizen Generated Data in Annex 4).
ii. Quality has to be assessed when using administrative data or other data sources. Ideally, when using administrative data, it should be assured that:
   - The population is consistent with the statistical output requirements
   - The classifications are appropriate
   - The underlying concepts are appropriate
   - The records are complete and up to date
   - The geographical coverage is complete and the measurement units are appropriately defined/identified
iii. When using other data sources (such as big data), the specific methodological challenges such as those linked to the statistical population and the veracity, volume, value, variety and volatility of such data have to be considered.

**Requirement 10.4:** The registers and the frames for surveys are frequently evaluated and adjusted.

Elements to be assured:
i. A systematic approach is in place for regular updating of the survey frames to ensure accurate coverage of the target population.
ii. For all surveys, the appropriate statistical population frames are updated regularly.
iii. Information gathered during the conduct of surveys is used to assess and improve the quality of the frame, especially with regard to its coverage and the quality of the contact variables and the auxiliary information (variables used in the sampling design).
iv. Frames to be sufficiently large and their usage well-coordinated to minimize respondent fatigue.

**Requirement 10.5:** KNBS and Statistical Units cooperate with the scientific community to improve methods and promote innovation in the development, production and dissemination of statistics.

Elements to be assured:
i. Collaboration with the scientific community is in place, for example through conferences, workshops, task forces and training/courses, to discuss relevant methodological and technological developments (e.g., with regard to exploiting new data sources).
ii. There are agreements in place with academic institutions on cooperation and the exchange of qualified personnel.
iii. Staff collaborate on methodological issues with colleagues at the international level.
iv. Regular participation and presentations at relevant national and international conferences is encouraged for the exchange of knowledge and experiences.
v. National and international conferences, seminars, workshops or similar events with the participation of the scientific community are organized by KNBS and Statistical Units.

### Principle 11: Assuring Cost-effectiveness

KNBS and Statistical Units should assure that resources are effectively and efficiently used. They should be able to explain to what extent set objectives were attained, that the results were achieved at a reasonable cost and are consistent with the principal purposes of the statistics. This principle is supported mainly by principle 5 of the Fundamental Principles of Official Statistics on sources of official statistics.

**Requirement 11.1:** The cost of producing all individual statistics is measured and analysed, and mechanisms are in place to assure the cost-effectiveness of statistical activities or processes.

Elements to be assured:
i. There is a system for registering cost and time used for all statistical products. Estimation of the time used on the main processes should be possible.
ii. The cost of producing statistics is well documented at each stage of the production process and is regularly reviewed and analysed across statistical products to assess the effectiveness of their production.
iii. Cost-benefit analyses are carried out to determine the appropriate trade-offs in terms of data quality.
iv. The cost-effectiveness of every statistical survey is assessed.
v. The need for each survey variable to be collected is justified.
vi. There is an ongoing review process that considers whether a particular programme is still operating in the most cost-effective way to meet its stated requirements.
vii. Data collection instruments are designed to minimize coding and editing cost and time.

**Requirement 11.2:** Procedures exist to assess and justify demands for new statistics against their cost.

Elements to be assured:
i. Demand for new statistics is regularly registered and assessed by statistical experts with regard to the proposed methodology and associated costs, and are discussed by management, based on inputs from users and in collaboration with other stakeholders.
ii. Before contemplating a new data collection, there are mechanisms to review whether already available data sources can be utilized with minimal impact on their purpose and quality.

**Requirement 11.3:** When introducing new statistics, a cost-benefit analysis is conducted.

Elements to be assured:
i. Procedures exist to assess the continuing need for all statistics, to determine whether any can be discontinued to free up resources.
ii. There are regular discussions by management on the usefulness of all statistics; the discussions include inputs from users, such as the results of user satisfaction surveys.
iii. The usage of different statistical products, including statistical databases, is monitored and assessed to evaluate their relevance.
iv. Users and stakeholders are informed and consulted about the possible discontinuation of statistical outputs.

**Requirement 11.4:** Modern information and communication technologies are applied to improve the performance of statistical processes.

Elements to be assured:
i. An appropriate IT strategy exists and is regularly reviewed and updated to improve the effectiveness and efficiency of the statistical processes.
ii. The IT architecture and hardware infrastructure are regularly reviewed and updated, and possibilities for innovation and modernization are identified.
iii. Routine clerical operations and statistical processes (e.g., data capture, coding, data editing, data validation, data exchange) are automated where possible and are regularly reviewed.
iv. Centralized IT and methodological units exist and provide possibilities for the pooling of resources and investments.

**Requirement 11.5:** Proactive efforts are made to improve the statistical potential of administrative data and other data sources.

Elements to be assured:
i. KNBS and Statistical Units provide input to the legislative process to obtain and maintain access to administrative and other data sources for statistical purposes, if needed.
ii. Appropriate arrangements (e.g., service-level agreements or national legislation) with owners or holders of administrative data and other data collections are made and updated as needed, specifying the access to and flow of data and metadata and other relevant aspects.
iii. An assessment of possible administrative data sources is carried out prior to launching any new survey.
iv. Data linking and integration methods are proactively pursued while ensuring data security and privacy.
v. Quality reports for administrative and other data used for official statistics are established by KNBS in cooperation with the data producers, owners or holders.

**Requirement 11.6:** KNBS and Statistical Units define, promote and implement integrated and standardized production systems.

Elements to be assured:
i. KNBS and Statistical Units have developed strategies to move to a more integrated and standardized statistical production system within their organization.
ii. KNBS and Statistical Units promote, share and implement standardized solutions that increase effectiveness and efficiency.
iii. The statistical business architecture of KNBS and Statistical Units are based on international standards and tools such as the GSBPM, the GAMSO, the Common Statistical Production Architecture (CSPA) and SDMX.

### Principle 12: Assuring Appropriate Statistical Procedures

Effective and efficient statistical procedures underpin quality and should be implemented throughout the statistical production chain. This principle is supported mainly by principle 2 of the Fundamental Principles of Official Statistics on Professional Standards, Scientific Principles, and Professional Ethics.

**Requirement 12.1:** Statistical processes are tested before implementation.

Elements to be assured:
i. The testing strategy is developed as part of the design phase of the statistical business process model.
ii. Data capture procedures and data collection tools and instruments such as electronic systems are tested to ensure simplicity and minimal intrusion on privacy and are adjusted if required before their implementation.
iii. Survey questionnaires are tested using appropriate methods (e.g., pilot survey, focus groups, etc.).
iv. Collection systems for administrative and other data are tested before use.
v. Data treatment and data processing procedures are tested and adjusted, if required and possible, prior to their actual application.
vi. Test results are taken into account in the implementation of the production process and are approved.
vii. In the case of integrating data from one or more sources, the quality of the linkage procedures is tested.

**Requirement 12.2:** Statistical processes are well established and regularly monitored and revised as required.

Elements to be assured:
i. KNBS and Statistical Units have documented procedures and guidelines that contain recommendations for appropriate methodologies to be used at different steps of the statistical production process.
ii. Documentation of production processes should follow the GSBPM.
iii. A policy for archiving data and statistics is in place and is followed.
iv. Statistical procedures employ internationally recognized statistical techniques.
v. Data from all data sources are reviewed and validated to identify potential problems, errors and discrepancies such as outliers, missing data and miscoding.
vi. When coding is done through an automated process, a team of well-trained coders is assigned to verify the automated coding and to handle un-coded cases.
vii. The effects of data editing and imputation are analyzed as part of assessing the quality of the data collection.
viii. All statistical databases are designed and arranged in a way that allows and facilitates data linkage, using unique identifiers for Statistical Units as appropriate while ensuring data security and privacy.

**Requirement 12.3:** Procedures are in place to effectively use administrative and other data sources for statistical purposes.

Elements to be assured:
i. KNBS and Statistical Units use tools and guidelines to assess the quality of the data of administrative and other data sources.
ii. Appropriate processes and software applications for the collection, processing and analyses of data of administrative and other data sources have been developed and implemented.
iii. Owners or holders of administrative and other data sources inform KNBS and Statistical Units of any changes in the data production process.
iv. Metadata related to administrative or other data sources are available to KNBS and Statistical Units, including concepts and definitions, classifications, coverage compared to target population and other quality aspects.
v. Documentation exists that describes how data from administrative and other sources meet the statistical requirements in terms of definitions, concepts and coverage, among other things.

**Requirement 12.4:** Revisions of statistics follow standard and transparent procedures.

Elements to be assured:
i. A revision policy that follows international standards and recommendations exists and is made public.
ii. Guidelines for revisions exist and are followed.
iii. Revisions of the published statistics are accompanied by metadata that provide necessary explanations.
iv. Indicators expressing the amount and types of revisions are computed and evaluated for improvement.

**Requirement 12.5:** Metadata and documentation of methods and different statistical processes are managed throughout the processes and shared as appropriate.

Elements to be assured:
i. There is a policy on metadata documentation linked to the statistical production processes.
ii. The policies and standards for maintaining and updating metadata are followed.
iii. Work on preparing statistics and their related metadata should be done concurrently.
iv. Metadata are captured throughout the statistical business process following the GSBPM and stored in a metadata management system.
v. Statistical methods and processes are documented in such a way that allows for the recreation of the entire statistical production process.

### Principle 13: Managing the Respondent Burden

Individuals, households or businesses that provide the data upon which statistical products are based are fundamental contributors to the quality of data and information. The requirement to collect data should be balanced against production costs and the burden placed on respondents. Mechanisms to maintain good relationships with providers of data and to proactively manage the respondent burden are essential to improving quality. This Principle is supported by principle 5 of the Fundamental Principles of Official Statistics on Sources of Official Statistics on prevention of misuse.

**Requirement 13.1:** The range and detail of requested information is limited to what is necessary.

Elements to be assured:
i. The availability and suitability of existing surveys and administrative or other data sources are explicitly considered before suggesting a new survey.
ii. Before establishing a new survey, a discussion should take place as to the possibility of producing the required data with less respondent burden by modifying or amending an existing survey or by linking the new survey with an existing survey (integrated survey system).
iii. The collection of each data item of a survey has to be explained and justified.
iv. The collection of any data items that are identical or similar to those collected in another survey is limited to what is considered necessary for verification and possible data linkage purposes.
v. When possible, surveys or parts of the information to be collected in the surveys are extracted or derived from available administrative registers.
vi. The burden on respondents is measured and included in a set of quality indicators and in the quality reports.

**Requirement 13.2:** Mechanisms are in place to promote the value and use of statistics to respondents.

Elements to be assured:
i. Information packages that provide respondents with important and necessary information about the survey and explain the value of official statistics are made available.
ii. Dissemination of the final reports or results of the census or sample survey to all, including respondents.
iii. Initiatives with community groups, schools, business advocates and others are undertaken to raise awareness of the value of official statistics.
iv. Electronic products are developed that give necessary statistical information to businesses and individuals, and these products are promoted through initiatives with communities and respondents.
v. Social media is used to promote participation in surveys and censuses.
vi. Standard practices are in place to obtain feedback from respondents and to respond to their requests and complaints in a regular manner.

**Requirement 13.3:** Sound methods, including IT solutions, are used in surveys to reduce or distribute the respondent burden.

Elements to be assured:
i. Appropriate sampling techniques are used to minimize sample sizes to achieve the target level of accuracy.
ii. Sample surveys are coordinated to distribute the burden on respondents.
iii. Multiple modes of the collection are offered to respondents, including electronic surveys.
iv. The collection of data is scheduled in consideration of the respondents' appropriate timing where applicable.
v. Frames are sufficient and their usage well-coordinated to minimize respondent fatigue.

**Requirement 13.4:** Data sharing, data linkage and the use of administrative and other data sources are promoted to minimize respondent burden.

Elements to be assured:
i. Documentation of data already available within the NSS, including archived data, exists and is shared.
ii. Procedures and technical tools for data sharing and data linkage within the NSS (e.g., formal agreements, web services, common databases) exist.
iii. Data repositories are shared among KNBS and Statistical Units for the production of official statistics and in compliance with confidentiality policies.
iv. Information on the quality of data to be linked exists (e.g., on coverage and linkage possibilities).
v. Use of administrative and other data as an alternative to survey data for producing official statistics is promoted throughout the NSS.

## Level D: Managing Statistical Outputs

Statistics serve the needs of national governments, research institutions, businesses, the general public and the international community. The output quality is measured by the extent to which the statistics are relevant, accurate and reliable, timely and punctual, readily accessible by and clear to users, and coherent and comparable across geographical regions and over time.

### Principle 14: Assuring Relevance

Statistical information should meet the current and/or emerging needs or requirements of its users. Without relevance, there is no quality. However, relevance is subjective and depends upon the varying needs of users. The challenge is to weigh and balance the conflicting needs of current and potential users to produce statistics that satisfy the most important and highest priority needs within the given resource constraints. Principle 14 is supported mainly by principle 1 of the Fundamental Principles of Official Statistics on relevance, impartiality, and equal access.

**Requirement 14.1:** Procedures are in place to identify users and their needs and to consult them about the content of the statistical work programme.

Elements to be assured:
i. There is legislation or some other formal provision that includes an obligation to consult with the main users of the statistics.
ii. Structured and periodic consultation processes (e.g., advisory councils and committees or working groups) with key stakeholders and users are in place to review the content of the statistical programme and the usefulness of existing statistics, and to identify requirements for new statistics.
iii. Feedback from a user support service, centre or hotline is analysed to understand and identify user needs.
iv. Data on the use of statistics (e.g., web analytics, number and types of downloads, subscribers to reports) are collected and analysed to improve statistical outputs.

**Requirement 14.2:** Users' needs and requirements are balanced, prioritized and reflected in the work programme.

Elements to be assured:
i. Users' priority needs are met and reflected in the work plan of KNBS and Statistical Units.
ii. Procedures are in place to prioritize various user needs in the work plan programme and strategic goals.
iii. Data on the use of statistics are analysed to support the setting of priorities.
iv. A periodic evaluation of the work plan is carried out to identify emerging needs and lower priorities.
v. Processes are in place to monitor and consult with stakeholders on the relevance and practical utility of existing statistics (with regard to scope, level of detail, cost, etc.) according to current and emerging user needs.

**Requirement 14.3:** Statistics based on new and existing data sources are being developed in response to society's emerging information needs.

Elements to be assured:
i. A mechanism such as Memoranda of Understanding (MoUs) are established to consider and experiment with new data sources to meet emerging information needs.
ii. Cooperation with the scientific community and owners or holders of new data sources is established to experiment with and pioneer the use of these data sources.
iii. Possibilities of exploiting new data sources are regularly discussed by management.

**Requirement 14.4:** User satisfaction is regularly measured and systematically followed up.

Elements to be assured:
i. User satisfaction surveys and user studies are regularly carried out and analyzed.
ii. Improvement actions arising from the user satisfaction surveys and user studies are identified and implemented.
iii. User satisfaction surveys include questions on the opinions of users about metadata availability.
iv. Measures to assess the satisfaction of main users of particular products are in place (e.g., specific user-satisfaction surveys and indicators, including timeliness, etc., at the product level).

### Principle 15: Assuring Accuracy and Reliability

KNBS and Statistical Units should develop, produce and disseminate statistics that accurately and reliably portray reality. The accuracy of statistical information reflects the degree to which the information correctly describes the phenomena it was designed to measure, namely, the degree of closeness of estimates to true values. This principle is supported mainly by principle 1 of the Fundamental Principles of Official Statistics on relevance, impartiality, and equal access.

**Requirement 15.1:** Source data, integrated data, intermediate results and statistical outputs are regularly assessed and validated.

Elements to be assured:
i. Systems for assessing and validating source data, integrated data, intermediate results and statistical outputs are developed and managed.
ii. Data are systematically checked and compared with data from other sources and over time.
iii. Results of statistics are compared with other existing information in order to ensure validity.

**Requirement 15.2:** Sampling errors are measured, evaluated and documented. Non-sampling errors are described and, when possible, estimated.

Elements to be assured:
i. Procedures and guidelines are available on how to measure and manage (e.g., reduce or balance) errors.
ii. Sources of possible sampling errors are identified and described.
iii. Sampling errors are measured and evaluated.
iv. Non-sampling errors are identified, described and evaluated.
v. Errors are analysed to identify improvement measures.
vi. Information about the sampling and non-sampling errors is made available to users as part of the metadata.

**Requirement 15.3:** Studies and analyses of revisions are carried out and used to improve data sources, statistical processes and outputs.

Elements to be assured:
i. Preliminary and revised data and statistics are clearly identified.
ii. Explanations about the timing, reasons for and the nature of revisions are made available.
iii. The revision policy follows standard and transparent procedures.
iv. Information on the size and direction of revisions for key indicators is used to improve the statistical processes.
v. Information on the size and direction of revisions for key indicators is provided and made public.

### Principle 16: Assuring Timeliness and Punctuality

KNBS and Statistical Units should minimize delays in making statistics available. Timeliness refers to how quicklyafter the reference date or the end of the reference period the data and statistics are made available to users. Punctuality refers to whether data and statistics are delivered on the promised, planned or announced dates. This principle is supported mainly by principle 1 of the Fundamental Principles of Official Statistics on relevance, impartiality, and equal access.

**Requirement 16.1:** The timeliness of statistics from KNBS's and Statistical Units comply with international standards or other relevant timeliness targets.

Elements to be assured:
i. The timeliness of statistics from KNBS and Statistical Unit complies with the dissemination standards of international organizations such as Special Data Dissemination Standard (SDDS).
ii. Divergences from international timeliness targets are monitored and, if the targets are not met, actions are taken to ensure compliance.
iii. The overall trade-offs between timeliness and other dimensions of quality (e.g., accuracy, cost and respondent burden) are given consideration when setting targets.

**Requirement 16.2:** The relationship with data providers is managed with regard to timeliness and punctuality needs.

Elements to be assured:
i. Agreements are in place with data providers on the planned delivery dates and delivery format.
ii. Procedures are in place to ensure the effective and timely flow of data from providers to KNBS and Statistical Units.
iii. Follow-up procedures are in place to ensure the timely receipt of data from providers.

**Requirement 16.3:** Preliminary results can be released when their accuracy and reliability is acceptable.

Elements to be assured:
i. The possibility and necessity of releasing preliminary data for key statistics is evaluated, while considering data accuracy and reliability.
ii. When preliminary statistics are released, they are clearly identified as such.
iii. Users are provided with appropriate information on the quality of the preliminary statistics.
iv. Preliminary results are revised according to the established revision policy. Final results are clearly distinguished from preliminary results.

**Requirement 16.4:** Punctuality is measured and monitored according to planned release dates, such as those set in a release calendar.

Elements to be assured:
i. The release calendar should be in place at least 3 months in advance before the publication of the relevant statistics.
ii. Punctuality or the rate of punctuality (i.e., rate of statistics published on time) is measured according to the release calendar.
iii. Information on the punctuality of the released statistics is discussed by management and made available to users.

### Principle 17: Assuring Accessibility and Clarity

KNBS and Statistical Units should ensure that the statistics they develop, produce and disseminate can be found and obtained without difficulty, are presented clearly and in such a way that they can be understood, and are available and accessible to all users on an impartial and equal basis in various convenient formats in line with open data standards. Provision should be made for allowing access to microdata for research purposes, in accordance with an established policy that ensures statistical confidentiality. This principle is supported mainly by Principle 1 of the Fundamental Principles of Official Statistics on relevance, impartiality, and equal access.

**Requirement 17.1:** Statistics are presented in a form that facilitates proper interpretation and meaningful comparisons.

Elements to be assured:
i. Statistics are presented in a clear and understandable manner to all users.
ii. Guidelines that describe the appropriate content and preferred formats and style (layout and clarity of text, tables and charts) of KNBS's and Statistical Units' outputs are available to authors of statistical publications and databases.
iii. Published statistics are open for free use and re-dissemination, provided that reference is made to the responsible agency.
iv. Staff training and development programmes are in place with regard to writing about statistics (for press releases, publication highlights or other explanatory texts).
v. Up-to-date methodological documents (on concepts, scope, classifications, the basis of recording, data sources, compilation methods and statistical techniques), as well as quality reports and the work programme of KNBS's and Statistical Units, are made available to the public.
vi. Explanatory texts accompanying the statistics are reviewed for clarity and readability.
vii. Meaningful comparisons are included in the publications when appropriate.
viii. Preliminary and revised data are identified and explained in published statistics.
ix. Metadata needed to understand and use the statistics are published together with the statistics.
x. A policy for archiving published statistics is in place.

**Requirement 17.2:** A data dissemination strategy and policy exists and is made public.

Elements to be assured:
i. The public is made aware that custom-designed outputs, statistics not routinely disseminated and longer time series can be provided on request when feasible, and it is instructed on how the data can be ordered. These outputs are made public if possible.
ii. Catalogues of publications and other services are made available to users.
iii. While official statistics are normally free and accessible for everyone, statistics that need to be produced on request might have a cost corresponding to the extra work they require. The pricing of special requests is fully transparent.
iv. A strategy has been developed and agreed upon with stakeholders for the release of anonymized data and microdata.

**Requirement 17.3:** Modern information and communication technology is used for facilitating easy access to statistics.

Elements to be assured:
i. Statistics are disseminated in various ways suitable for all users, with KNBS's website providing a central entry point.
ii. Users are able to extract data from statistical databases through public interfaces in the most appropriate and common formats (xlsx, csv, html, etc.).
iii. Statistical data can be accessed through an application programming interface.
iv. Statistics are disseminated in ways that facilitate re-dissemination by the media.
v. KNBS and Statistical Units consults users on a regular basis to discover the formats of dissemination they most prefer.
vi. Agreements with key users are established for the efficient and regular transmission of statistics and data.
vii. Technical solutions for access to anonymized data are available.
viii. Explicit consideration has been given to trade-offs between accessibility and confidentiality (i.e., level of detail in tables).

**Requirement 17.4:** Access to microdata is allowed for research purposes, subject to specific rules and protocols on statistical confidentiality that are posted on KNBS's and Statistical Units' website.

Elements to be assured:
i. KNBS and Statistical Units control or monitor the access of researchers to microdata by providing the microdata in a secure environment.
ii. Researchers are regularly consulted about the effectiveness of the microdata access arrangements.
iii. Remote access facilities are available for accessing microdata, with appropriate controls.

**Requirement 17.5:** Mechanisms are in place to promote statistical literacy.

Elements to be assured:
i. KNBS and Statistical Units have a strategy to manage media relationships and maintain regular contact with the media.
ii. KNBS and Statistical Units arrange regular training and outreach for journalists.
iii. KNBS and Statistical Units arrange training for students on how to use statistics.
iv. The publication of articles on statistical issues, and how statistics should be used properly, is encouraged.

**Requirement 17.6:** KNBS and Statistical Units have a dedicated focal point that provides support and responds to inquiries from users in a timely manner.

Elements to be assured:
i. Well-known user support services are available to give prompt assistance to users to help them access and interpret the data.
ii. User support services are appropriately staffed to support a wide range of users.

**Requirement 17.7:** Users are kept informed about the quality of statistical outputs.

Elements to be assured:
i. Standards for quality reports for different users' needs, are defined.
ii. Published statistics are accompanied by standard quality reports, including information on the periodicity of the statistics, data sources, production methods and quality (i.e., accuracy and reliability, timeliness and punctuality, coherence and comparability, accessibility and clarity).
iii. Results from quality assessments or reviews are made public.

### Principle 18: Assuring Coherence and Comparability

KNBS and Statistical Units should develop, produce and disseminate statistics that are consistent, meaning it should be possible to combine and make joint use of related data, including data from different sources. Furthermore, statistics should be comparable over time and between areas. This Principle is supported mainly by Principle 1 of the Fundamental Principles of Official Statistics on relevance, impartiality, and equal access.

**Requirement 18.1:** International, regional and national standards are used with regard to definitions, units, variables and classifications.

Elements to be assured:
i. KNBS and Statistical Units promote the adoption of national, regional or international statistical standards.
ii. Guidelines, a common repository of statistical concepts, definitions of units and variables, and classifications and other mechanisms exist.
iii. Compliance with international, regional or national standards for statistical production is periodically assessed. Any deviations from these standards are identified and included in the publicly available metadata, along with reasons for such deviations.

**Requirement 18.2:** Procedures or guidelines are in place to ensure and monitor internal, intrasectoral and cross-sectoral coherence and consistency.

Elements to be assured:
i. Statistics derived from different sources or with different periodicities (e.g., monthly, quarterly, yearly) are compared and any differences are explained and reconciled, as appropriate.
ii. Cooperation and the exchange of knowledge among individual statistical programmes and domains is promoted.
iii. Process-specific procedures and guidelines are available to ensure that outputs are internally coherent.
iv. Before new statistics or statistical programmes are launched, the conceptual and methodological relationship with existing statistics is analysed.
v. Statistical outputs are compared with results of other statistical or administrative sources that provide the same or similar information on the same subject matter, and divergences are identified and explained to users.
vi. Internal procedures or guidelines are developed in order to ensure and monitor internal coherence and consistency.
vii. Procedures and guidelines are developed in order to ensure that results from different sources can be combined. Compliance is periodically assessed.

**Requirement 18.3:** Statistics are kept comparable over a reasonable period of time and between geographical areas.

Elements to be assured:
i. Changes in methods of data compilation are clearly identified, described and analysed to facilitate the interpretation of the results.
ii. Quality reporting includes a section on the assessment of internal consistency and comparability over time and with related statistics.
iii. Breaks in a series are explained and the methods for ensuring reconciliation over a period of time are made publicly available.
iv. Effects of changes in methodologies on final estimates are assessed and appropriate information is provided to users.
v. Significant changes in the society and phenomena to be measured are reflected by appropriate changes to concepts, classifications, definitions and target populations.
vi. Differences within geographical areas or at the country level due to different concepts or methodologies are explained.

### Principle 19: Managing Metadata

KNBS and Statistical Units should provide information covering the underlying concepts and definitions of the data collected and statistics produced, the variables and classifications used, the methodology of data collection and processing, and indications of the quality of the statistical information in general, sufficient information to enable the user to understand all of the attributes of the statistics, including their limitations. This Principle is supported mainly by principle 3 of the Fundamental Principles of Official Statistics on accountability and transparency.

**Requirement 19.1:** The metadata management system of KNBS and other statistical units is well defined and documented.

Elements to be assured:
i. A strategy, guidelines and procedures are in place for metadata management and dissemination.
ii. Metadata management is recognized as the responsibility of all staff.

**Requirement 19.2:** Metadata are documented, archived and disseminated according to internationally accepted standards.

Elements to be assured:
i. International, regional, national or internal standards are used for metadata documentation, management and archiving.
ii. Procedures are in place to ensure that metadata are documented according to standardized metadata systems and are regularly updated.
iii. Metadata are made available at the same time as the data and statistics to which they pertain.
iv. The dissemination of metadata is tailored to different needs, such as those of producers and users of statistics.
v. A systematic way to archive metadata is available that also ensures that the metadata are accessible for reuse in the future.
vi. A glossary of statistical concepts is publicly available.

**Requirement 19.3:** Staff training and development programmes are in place on metadata management and related information and documentation systems.

Elements to be assured:
i. Process managers are trained to properly document the data and describe the relevant processes.
ii. KNBS's and Statistical Units' staff participate in international metadata forums.