# Quality Context and Concepts

## Introduction

In recent years, new data sources, data providers and statistics producers have emerged, fueled by technological advances and new demands for detailed and timely data for policy making to address various development agendas. This new data ecosystem poses challenges and opportunities for official statistics. For instance, in the future, national statistical offices may see their role as a producer of official statistics diminished while adopting a new role as a curator of data and statistics produced by others. There is, therefore, a need for a National Quality Assurance Framework (NQAF) that provides a coherent and holistic system for statistical quality management that guarantees trust in the quality of official statistics. Official statistics need to be produced in an objective, transparent and professionally independent manner, in order to achieve and maintain public trust (UNCTAD, 2019). In light of this, the UN-NQAF manual for Official Statistics was adopted in 2019 to guide countries in the implementation of their respective NQAF (United Nations, 2019). The 19 quality principles and their associated requirements from the United Nations National Quality Assurance Framework (UN NQAF) manual are all borrowed in the development of the Kenya Statistical Quality Assurance Framework (KeSQAF). KeSQAF aims to address quality assurance in different circumstances and situations, thereby supporting the country in safeguarding the role of official statistics as a trusted source of information in a changing environment. This section presents the rationale for developing the quality assurance framework, the benefits of KeSQAF and the policies, strategies and frameworks supporting KeSQAF. Definitions of the adopted quality dimensions are also presented in this section.

## Quality Context

### Rationale for a Quality Assurance Framework

The Kenya National Bureau of Statistics (KNBS) is the National Statistics office in Kenya and is mandated to collect, compile, analyse, publish, and disseminate statistical information for public use. It is the principal agency for official statistics produced in the country. Official statistics are not only indispensable inputs for planning, monitoring and assessing attainment of the targets of the national development agenda, strategic objectives of businesses and research objectives of academicians, but are also useful for other evidence-based decision-making.

Given KNBS's obligation to provide statistics that inform decision-making and the need to provide leadership to members of the NSS and other producers of statistics, there is a need for a framework to support the production of high-quality statistics. The UN NQAF manual recommends the use of the Generic Statistical Business Process Model (GSBPM) which provides a roadmap on the various sets of business processes required to produce official statistics. GSBPM outlines steps in the data production process that include, identification of needs, design, data collection and processing, data analysis and reporting, dissemination and documentation and lastly, evaluation. Care has to be taken to guard against errors in the statistical business process and to mitigate and/or correct deficiencies by providing supportive legal, administrative and technological infrastructure and institutional environment. This is the context in which KeSQAF has been developed to manage the quality of the organization's services, statistical processes and related products, as well as communication with stakeholders in a systematic and formalized way.

The quality assurance framework provides transparency and clarity necessary to manage and respond to data users' expectations, queries and demands while bolstering the credibility of the organization. It is the responsibility of KNBS to clearly articulate the concepts and definitions that form the basis for the statistics produced while outlining the methodologies used. It is also KNBS's responsibility to check on erroneous interpretation and misuse of statistics. This is especially useful for addressing instances when the reasonableness of statistics published across NSS is questioned by stakeholders whose concerns may be based on the limited understanding of the methodologies used in generating the statistics.

The KNBS is part of a global statistical system characterized by increasing interconnectedness, a dynamic knowledge economy and the use of rapidly changing technology that requires openness and adherence to scientific and professional standards, including the use of a common architectural framework that allows for the sharing and exchange of information. The Bureau, therefore, does not operate in isolation but with other producers of statistics locally, regionally and internationally. Information sharing with its partners necessitates adequate provision for access to data, with due regard for confidentiality, coherence and comparability of statistics. Kenya ascribes to global, continental and regional development agendas such as Agenda 2063 on Africa Charter for Development of Statistics and the 2030 Global Development Agenda for Sustainable Development implying that statistics of high quality are necessary for tracking progress in attaining these development goals.

The UN Fundamental Principles of Official Statistics (UNFPOS) and Principles Governing International Statistical Activities (PGISA) promote coordination and cooperation among national organizations for official statistics to improve systems of official statistics globally. Against this background, there is a need for modernization of the Bureau's statistical production and services which is also being driven by the need to reduce the response burden and improve efficiencies in the production of official statistics. Additionally, data users have an increasing demand for more timely and accurate data and there is growing competition from alternative data producers and researchers moving up the statistical value chain. This, therefore, requires that KNBS steps up in the implementation of its mandate to ensure that the statistics produced across NSS are of high quality.

### Benefits of the Kenya Statistical Quality Assurance Framework

The quality assurance framework has a well-defined and responsive structure that provides context for quality concerns, activities and initiatives and explains the relationships between the various quality procedures and tools. The framework provides a single platform to record and reference the full range of current quality concepts, dimensions and practices and is forward-looking since it is flexible to take into account future actions and activities.

The quality assurance framework also serves to formalize both operational standards and criteria for evaluating the fitness of statistical data for their required purposes, as well as the methodologies used for data collection, processing, analysis and dissemination, and strategic and managerial issues of statistics.

In addition, KeSQAF aims to improve consistency and efficiency in the NSS by reducing duplication of efforts; normalizing the use of international concepts, definitions, classifications, standards, sampling frames, and methodologies, where appropriate; and, creating datasets that are responsive to data sharing demands.

KeSQAF aims at increasing effectiveness and efficiency in the production of statistics in the Country. The framework also forms a foundation for validating data from both primary and alternative sources.

### Policies, Strategies and Frameworks Supporting the Development and Implementation of KeSQAF

The development and implementation of KeSQAF is supported by various legal frameworks, strategies, policies, procedures and statistical quality frameworks. These include the:

a. Statistics Act, 2006;

b. Kenya Strategy for Development of Statistics (KSDS);

c. ISO 9001:2015 standards;

d. Existing Data Quality Assessment Frameworks (DQAFs);

e. United Nations National Quality Assurance Framework (UN-NQAF);

f. UN Principles Governing International Statistical Activities;

g. African Charter on Statistics;

h. International Statistical Institute's (ISI) Declaration on Professional Ethics;

i. Statistical Data and Metadata Exchange (SDMX);

j. European Statistics (Eurostat) Code of Practice (CoP).

## Quality Concepts

Quality is a multidimensional concept, which means the degree to which a set of inherent characteristics fulfils requirements. Quality is in reference to statistical output, the statistical process that produced it, the institutional environment housing the process, or the whole statistical system. The KNBS adopts the "Fit for purpose" approach, whereby statistics produced are appropriate and are of necessary standards for their intended use. This, therefore, means that the users of statistics will be continually engaged so that data produced in the Country is of the highest standard, integrity and credibility and addresses gaps/needs of the users. Data quality is expressed in terms of dimensions. In line with international best practices and recommendations, KNBS has adopted 11 key quality dimensions for assuring statistical quality. These are relevance, accuracy, reliability, timeliness, punctuality, accessibility, clarity/interpretability, coherence, consistency, methodological soundness and integrity. It is important to note that these quality dimensions strongly focus on the quality of the statistical output and are, therefore, a subset of the 19 quality principles adopted in KeSQAF.

### Relevance

is the "degree to which statistical information meets the real or perceived needs of clients." This dimension of quality addresses how useful official statistics are for the issues that are important to users. Resource constraints necessitate the identification of and responsiveness to the most important needs among many user needs.

### Accuracy

refers to the "closeness of computations or estimates to the unknown exact or true values that the statistics were intended to measure." This reflects the degree of nearness that official statistics have achieved in correctly representing the phenomena they measure. This can be expressed in terms of quantitative measures of accuracy, including possible sources of error such as coverage, sampling, non-response and response error rates; or qualitative assessment indicators.

### Reliability

is closely associated with accuracy and speaks of the "closeness of the initial estimated value to the subsequent estimated value." Consistently large differences between subsequent estimates to an initial estimate suggest possible bias in the initial estimate, while random large gaps between subsequent estimates and an initial estimate may indicate a need to re-assess the timeliness of subsequent estimates.

### Timeliness

pertains to the "length of time between data availability and the event or phenomenon they describe." This references both:

a) the time lapse between the end of a reference date/period for data collection and receipt of the data for compilation and processing (timeliness of source data), and

b) the time lapse between the end of a reference date/period and data dissemination (timeliness of output).

### Punctuality

is closely associated with timeliness and is the "time lag between the actual delivery of the data and the target date when it should have been delivered." This relates to whether or not data are disseminated on scheduled release dates. Data that is punctual may still be considered untimely if the release date lags too far behind its reference period (i.e., the time of the occurrence of the event/phenomenon), rendering it less useful or useless for decision-making.

### Accessibility

refers to "the ease and conditions under which statistical information can be obtained." This relates not only to how easily data can be accessed by users but also to the form the data are in and the means through which users have access to the data.

### Clarity

is "the extent to which easily comprehensible metadata are available, where these metadata are necessary to give a full understanding of statistical data." It addresses whether or not statistical data are complemented by descriptive information about the data's quality and limitations and if additional assistance is available to users by providers to enable users to work with the data to meet their needs.

### Coherence

is the "adequacy of statistics to be combined in different ways and for different uses. It refers to comparisons between statistics for the same or largely similar populations." Coherence in statistics is the degree to which the data constitute a logical picture of the population they are describing. For example, in the domain of labour statistics, the employed and unemployed must account for 100 per cent of the labour force.

### Consistency

refers to statistics having "logical and numerical coherence."

### Methodological Soundness

is "the extent to which the methodology used to compile statistics complies with the relevant international standards, including the professional standards enshrined in the UN Fundamental Principles for Official Statistics."

### Integrity

refers to "values and related practices that maintain confidence in the eyes of users in the agency producing statistics and ultimately in the statistical product." It is adherence to ethical and professional standards to ensure that transparency, accountability, methodological soundness, and professional independence guide the policies and practices of producing and disseminating official statistics.