# Environment Statistics

## Environmental Conditions and Quality

Environmental conditions and quality refer to the physical, chemical, biological, and socio-economic factors that characterize the environment and determine its ability to sustain life. It includes aspects such as air, water, soil quality, and the natural habitats that support ecosystems and human activities.

### Weather

Weather is the state of the atmosphere of a given place at a given time. The elements of weather include, but are not limited to, rainfall, temperature, pressure, wind, cloud cover and humidity.

### Climate

Climate is the average weather pattern in a place over a period of at least thirty years as defined by the World Meteorological Organization

### Climate change

Climate change is a permanent shift in the state of climate that persists for an extended period (decades or longer). It is attributed directly or indirectly to human (anthropogenic) activity that alters the composition of the global atmosphere

### Climate variability

Climate variability refers to fluctuations or deviations in the mean state of climate over a given period ranging from months, season or years and space when compared to long-term statistics for the same calendar period

### Environment

The totality of all the external conditions (physical, biological, and socio-economic) affecting the life, development, and survival of an organism.

### Meteorological

Related to the science of the earth's atmosphere, especially as it relates to weather and climate.

### Hydrographical

The branch of applied sciences which deals with the measurement and description of the physical features of oceans, seas, coastal areas, lakes and rivers, as well as with the prediction of their change over time, for the primary purpose of safety of navigation and in support of all other marine activities.

### Geological

Relating to the study of the earth's physical structure and substance.

### Geographical

Anything related to the Earth's physical features, locations, places, or the spatial relationships between them.

### Biological

Anything related to living organisms, life processes, or the science of life (biology).

## Environmental Resources and their use

This sub-domain focuses on the natural resources available in the environment, their extraction, utilization, and management. It encompasses renewable and non-renewable resources, as well as the sustainable and unsustainable practices that affect their availability and quality.

### Natural resource accounting

Natural resource accounting is an accounting system that deals with stocks and stock changes of natural assets, comprising biota (produced or wild), subsoil assets (proved reserves), water and land with their aquatic and terrestrial ecosystems.

### Natural resources

Natural resources are natural assets (raw materials) occurring in nature that can be used for economic production or consumption.

### Sustainable Use

A use of resources which does not compromise the right to use the same resource (e.g., land, forest, water etc) by future generations.

### Eco-system

The complex of plant and animal communities and their inter-relations with each other and with non-living environment.

### Biodiversity

The total variety of life on earth in all its forms, levels, and combinations. It includes diversity within genetic differences, species differences and eco-system differences in each area.

### Biomass

Total living weight (generally dry weight) of all organisms in a particular area or habitat. It is sometimes expressed as weight per unit area of land or per unit volume of water.

### Wetland

A topographically delineated area of land where all precipitation collects and drains off into a common outlet, such as a river, lake, reservoir, or ocean.

### Water Catchment Area

A geographic area where all rainfall and surface runoff drains into a common water body, such as a river, lake, or reservoir.

### Watershed

An area separating one or more water catchments.

### Water Conservation

The control and development of water resources, both surface and underground water, in a manner that promotes sustainable use.

## Residuals

Residuals refer to materials, substances, or energy flows that are released back into the environment as a result of human activities, industrial processes, or natural systems. These residuals often have potential impacts on environmental quality and can lead to pollution or degradation of natural resources.

### Air Pollution

The presence of contaminants or pollutant substances in the air at levels that interfere with the health or welfare of human and other organisms or can produce other harmful environmental effects.

### Land Degradation

The physical, chemical, or biological impairment of the attributes of land.

### Biological Sludge

The byproduct of a biological treatment of effluents (waste products from industries). The biological sludge can then be used for soil improvement. The amount of waste that can be treated with biological means for other useful purposes

### Greenhouse Gas Emission

It is the emission of those gases that, by affecting the radiation transfer through the atmosphere, contribute to the greenhouse effect.

### Emission

Discharge of substances, heat, and sound into the atmosphere, water and soil from sources such as smokestacks, vents, surface areas of commercial or industrial facilities etc.

### Waste

Any material (solid, liquid, or gaseous) discharged into the environment without immediate use.

### Solid Waste

Any useless and sometimes hazardous material with low liquid content. Solid wastes include municipal garbage, industrial and commercial waste, sewage sludge, wastes resulting from agricultural and animal husbandry operations and other connected activities, demolition wastes and mining residues.

### Biological Waste

Waste containing natural organic materials (remains of plants, animal excreta, biological sludge from waste-water treatment, plants, etc) and capable of undergoing biological degradation.

### Agricultural Waste

Any waste produced as a result of various agricultural operations. It includes manure and other wastes from farms, poultry houses and slaughter-house, harvest waste, fertilizer run-offs from fields, pesticides that enter into water, air or soils, etc.

### Industrial Waste

Liquid, solid and gaseous wastes originating from the manufacture of specific products.

### Water Pollution

The presence in water of harmful and objectionable materials (obtained mainly from sewers, industrial wastes, and rainwater run-offs) and in sufficient concentrations to make the water unfit for use.

## Hazardous events and disasters

Hazardous events and disasters refer to natural or human-induced occurrences that significantly disrupt the environment, cause loss of life or property, and negatively impact ecosystems, communities, and economies. These events are often classified based on their origin (natural or anthropogenic) and can vary in scale, frequency, and severity.

### Inter Tropical Convergence Zone (ITCZ)

This is a belt of low pressure which circles the Earth generally near the equator where the trade winds of the Northern and Southern Hemispheres come together. It is characterized by convective activity which generates often vigorous thunderstorms over large areas

## Human Settlements and Environmental Health

This sub-domain focuses on the interaction between human settlements (such as urban, suburban, and rural areas) and environmental factors that influence public health. It includes aspects like housing, sanitation, water supply, waste management, and the overall livability of human environments, as well as the environmental determinants of health.

### Environmental Sanitation

Improvement of conditions in households that affect human health by means of drainage and disposal of sewage, human excreta, and refuse.

### Safe Drinking Water

Clean water supplied from an improved water source, such as a borehole/shallow well fitted with a hand pump, or a protected spring or gravity flow scheme, or treated piped water, subject to maintenance of a safe drinking-water chain.

### Sanitation

Encompasses the isolation/management of excreta from the environment, maintenance of personal, domestic and food hygiene, safe disposal of solid and liquid wastes, maintaining a safe drinking-water chain and vector control.

### Population using basic drinking water service

Population using an improved drinking water source/facility with a total collection time of 30 minutes or less for a round-trip, including queuing

### Population using safely managed drinking water services

Population using an improved source of drinking water (improved source of drinking water include: Piped water into dwelling yard or plot, borehole or tube wells, protected dug wells, protected spring, rainwater and packaged or delivered water) which is located on premises, available when needed and free of (faecal and priority chemical) contamination.

### Population using basic sanitation services

Population using an improved sanitation facility (improved Sanitation facilities include: flush/pour flush to piped sewer system, septic tank or latrine; ventilated improved pit latrine, composting toilet or pit latrine with slab) which is not shared with households

### Population using safely managed sanitation services

Population using improved sanitation facilities (improved sanitation facilities include: flush or pour flush to piped sewer systems; septic tanks or pit latrine; ventilated improved pit latrine; composting toilet or pit latrine with slab) which is not shared with other households and where excreta are treated and disposed in situ or transported and treated offsite

## Environmental protection, Management and Engagement

This sub-domain focuses on activities, policies, and measures designed to preserve, manage, and improve the quality of the environment. It includes actions aimed at mitigating environmental degradation, promoting sustainable resource use, and fostering public and institutional engagement in environmental conservation.

### Conservation

Management of human use of organisms or ecosystems so that it may yield the greatest sustainable benefit to present generations while maintaining its potential to meet the needs and aspirations of future generations.

### Environmental Impact Assessment (EIA)

A systematic examination conducted to determine whether a project, policy, program, etc, will have any adverse impacts on the environment. The EIA also provides plans for mitigation of the adverse effects.

### Environmental Audit (EA)

The systematic documented, periodic and objective evaluation of how activities and processes of an ongoing project to determine how far these activities and programs conform with the approved environmental management plan of that specific project and sound environmental management practices

### Environmental Protection

Any activity to maintain or restore the quality of the environment, through preventing the degradation of air, land, and water resources.

### Afforestation

An artificial establishment of a forest by planting or seeding in an area of non-forest land.

### Reforestation

An artificial establishment of a forest by planting or seeding in an area which was originally a forest.

### Deforestation

The process of replacement of forests by other land use or vegetation types.

## Environment statistics, n.e.c.

This category includes aspects of environmental statistics that do not fit into the above predefined sub-domains such as environmental conditions, resources, residuals, hazardous events, or human settlements. It serves as a broad and flexible classification for emerging, interdisciplinary, or complex environmental topics and statistical frameworks.

### Species

All the individuals and populations of a particular kind of organism maintained by biological mechanisms that result in their breeding only with their own kind.

### Fauna

All animal life.

### Flora

All plant life.

### Greenhouse Gases

These are Gases that trap the infra-red (heat) radiation in the Earth's atmosphere, producing the greenhouse effect. The two major greenhouse gases are water vapor and carbon dioxide.

### Greenhouse Effect

The trapping of infra-red (heat) radiation from the Earth's   surface in the atmosphere by the greenhouse gases.

### Global Warming

The increase in the average temperature of the earth's atmosphere and oceans that has been observed in the recent decades. Carbon dioxide is responsible for most of global warming, although methane and other greenhouse gases also warm the climate.

### Synoptic Weather Stations

Meteorological observation stations that collect and report weather data at regular, standardized times (usually every 6 hours), contributing to regional and global weather monitoring and forecasting systems. The meteorological information is collected at synoptic time 00h00, 06h00, 12h00, 18h00 (UTC) and at intermediate synoptic hours 03h00, 09h00, 15h00, 21h00 (UTC).